# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84a5606bec812d46fdaab359198144543648b46f8c6eaffd8d33fb555da7169ddf4aa49daa7a6a8fcc580be5db5a6728f80cc108550c38a39c214e6a273bd366

test:
  secret_key_base: c2cfb0547e21f8cb790f42b88d5e7c5c3f5a14c30e5da108543615fbf5b688ba57b6b114435856f492d51f9cd4674600e5169c82625ac6decf9d6c05d68afd9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
